services:
- type: web
  name: v2-booking-backend
  env: node
  rootDir: backend
  buildCommand: npm install
  startCommand: npm start

- type: web
  name: v2-booking-frontend
  env: static
  rootDir: frontend
  buildCommand: npm install && npm run build
  staticPublishPath: dist
